spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/yaoyebufan/spring-cloud-config
          search-paths: respo
          username: yaoyebufan
          password: yao960408
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
      base-url: http://localhost:9411

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/